version: "2"
services:
  app:
    container_name: supplement-server
    restart: always
    build: .
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME}
      - MONGODB_PORT=${MONGODB_PORT}
      - ADMIN_CODE=${ADMIN_CODE}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3032:3032"
    links:
      - mongo
  mongo:
    container_name: supplement-db
    image: mongo:3.5
    command: mongod --port 27017 --bind_ip_all 
    volumes:
      - /data/supplement-db:/data/db
    ports:
      - "27017:27017"